services:
  master:
    image: master-node
    ports:
      - "8080:8080"
    networks:
      - dfs-network

  worker:
    image: worker-node
    deploy:
      replicas: 5
    depends_on:
      - master
    ports:
      - "8081:8081"
    networks:
      - dfs-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - dfs-network

networks:
  dfs-network: