services:
  master:
    image: master-node
    ports:
      - "8080:8080"
    networks:
      - FrostByte_network

  worker:
    image: worker-node
    deploy:
      replicas: 5
    restart: always
    depends_on:
      - master
      - mongodb
    networks:
      - FrostByte_network

  mongodb:
    image: mongo:8.0.6
    ports:
      - "27017:27017"
    networks:
      - FrostByte_network
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb


networks:
  FrostByte_network:

volumes:
 mongo_data:
 mongo_config: