services:
  master:
    image: master-node
    ports:
      - "8080:8080"
    networks:
      - dfs-network

  worker:
    image: worker-node
    deploy:
      replicas: 5
    depends_on:
      - master
    networks:
      - dfs-network


networks:
  dfs-network: